import Head from 'next/head'
import Image from 'next/image'
import Barnahus from '../components/barnahus'
import Community from '../components/community'
import Engage from '../components/engage'
import Footer from '../components/footer'
import Managing from '../components/managing'
import Mauritius from '../components/mauritius'
import Mffais from '../components/mffais'
import Optimize from '../components/optimize'
import Ping from '../components/ping'
import Procrastination from '../components/procastination'
import Projects from '../components/projects'
import Rooms from '../components/rooms'
import Solutions from '../components/solutions'
import Stake from '../components/stake'
import Tabs from '../components/tabs'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div >
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

     <section>
      <Solutions />
      <Engage />
      <Optimize />
      <Tabs />
      <Procrastination />
      <Ping />
      <Community />
      <Rooms />
      <Mffais />
      <Mauritius />
      <Managing />
      <Barnahus />
      <Stake />


      <Projects />
      <Footer />
      
     </section>
    </div>
  )
}
